version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - ../server/.env
    volumes:
      - "${POSTGRES_DATA_VOLUME:-./store/pg_data}:/var/lib/postgresql/data/"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: on-failure

  mongodb:
    image: mongo:latest
    env_file:
      - ../server/.env
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - "${MONGO_DATA_VOLUME:-./store/mongo_data}:/data/db/"
    ports:
      - "${MONGO_PORT:-27017}:27017"
    restart: on-failure

  server:
    build:
      context: .
      dockerfile:
        Dockerfile
    env_file:
      - ../server/.env
    ports:
      - "${PORT:-4000}:4000"
    restart: on-failure

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure

  client:
    image: client
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "5001:3000"
