export enum SymbolType {
    PLUS_MINUS = '+-',
    OPENING_PARENTHESIS = '(',
    CLOSING_PARENTHESIS = ')',
    PLUS = '+',
    MINUS = '-',
    MULTIPLY = '*',
    DIVIDE = '/',
    CE = 'CE',
    C = 'C',
    ZERO = '0',
    ONE = '1',
    TWO = '2',
    THREE = '3',
    FOUR = '4',
    FIVE = '5',
    SIX = '6',
    SEVEN = '7',
    EIGHT = '8',
    NINE = '9',
    COMMA = ',',
    DOT = '.',
    EMPTY = '',
    EQUAL = '='
}